version: '3.7'

services:
  paper:
    build: .
    container_name: inventory_share
    stdin_open: true
    tty: true
    ports:
      - 25565:25565
      - 5005:5005
    volumes:
      - ./.docker:/data
    entrypoint:
      - /docker-setup-plugin
      - https://github.com/noonmaru/kotlin-plugin/releases/download/1.4.21/Kotlin.jar
      - https://github.com/noonmaru/auto-reloader/releases/download/1.0.1/AutoReloader.jar
